name: Keep App Alive

on:
  schedule:
    - cron: '*/6 * * * *'   # 每 15 分钟运行
  workflow_dispatch:         # 允许手动触发

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping your service
        run: |
          curl -s https://youtube-webhook-jibi.onrender.com/youtube-webhook/
